# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Connectr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Connectr
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'SwiftInstagram'
  pod 'TwitterKit'
  pod 'Alamofire'
end
